export const pokemonSprites: Record<string, any> = {
  CHARMANDER: require("../assets/pokemon/CHARMANDER.png"),
  CHARMELEON: require("../assets/pokemon/CHARMELEON.png"),
  CHARIZARD: require("../assets/pokemon/CHARIZARD.png"),
  BULBASAUR: require("../assets/pokemon/BULBASAUR.png"),
  IVYSAUR: require("../assets/pokemon/IVYSAUR.png"),
  VENUSAUR: require("../assets/pokemon/VENUSAUR.png"),
  SQUIRTLE: require("../assets/pokemon/SQUIRTLE.png"),
  WARTORTLE: require("../assets/pokemon/WARTORTLE.png"),
  BLASTOISE: require("../assets/pokemon/BLASTOISE.png"),
  EEVEE: require("../assets/pokemon/EEVEE.png"),
  FLAREON: require("../assets/pokemon/FLAREON.png"),
  VAPOREON: require("../assets/pokemon/VAPOREON.png"),
  LEAFEON: require("../assets/pokemon/LEAFEON.png"),
  PIDGEY: require("../assets/pokemon/PIDGEY.png"),
  PIDGEOTTO: require("../assets/pokemon/PIDGEOTTO.png"),
  PIDGEOT: require("../assets/pokemon/PIDGEOT.png"),
  JIGGLYPUFF: require("../assets/pokemon/JIGGLYPUFF.png"),
  WIGGLYTUFF: require("../assets/pokemon/WIGGLYTUFF.png"),
  VULPIX: require("../assets/pokemon/VULPIX.png"),
  NINETALES: require("../assets/pokemon/NINETALES.png"),
  PONYTA: require("../assets/pokemon/PONYTA.png"),
  RAPIDASH: require("../assets/pokemon/RAPIDASH.png"),
  PSYDUCK: require("../assets/pokemon/PSYDUCK.png"),
  GOLDUCK: require("../assets/pokemon/GOLDUCK.png"),
  POLIWAG: require("../assets/pokemon/POLIWAG.png"),
  POLIWHIRL: require("../assets/pokemon/POLIWHIRL.png"),
  POLIWRATH: require("../assets/pokemon/POLIWRATH.png"),
  BELLSPROUT: require("../assets/pokemon/BELLSPROUT.png"),
  WEEPINBELL: require("../assets/pokemon/WEEPINBELL.png"),
  VICTREEBEL: require("../assets/pokemon/VICTREEBEL.png"),
  ODDISH: require("../assets/pokemon/ODDISH.png"),
  GLOOM: require("../assets/pokemon/GLOOM.png"),
  VILEPLUME: require("../assets/pokemon/VILEPLUME.png"),
  GASTLY: require("../assets/pokemon/GASTLY.png"),
  HAUNTER: require("../assets/pokemon/HAUNTER.png"),
  GENGAR: require("../assets/pokemon/GENGAR.png"),
  LITWICK: require("../assets/pokemon/LITWICK.png"),
  LAMPENT: require("../assets/pokemon/LAMPENT.png"),
  CHANDELURE: require("../assets/pokemon/CHANDELURE.png"),
  MIMIKYU: require("../assets/pokemon/MIMIKYU.png"),
};

export const pokeballSprites: Record<string, any> = {
  normal: require("../assets/balls/pokeball.png"),
  superball: require("../assets/balls/superball.png"),
};

export const medalSprites: Record<string, any> = {
  stone: require("../assets/medals/stone.png"),
  knuckle: require("../assets/medals/knuckle.png"),
  dynamo: require("../assets/medals/dynamo.png"),
  heat: require("../assets/medals/heat.png"),
  feather: require("../assets/medals/feather.png"),
  rain: require("../assets/medals/rain.png"),
};
