export const pokemonSprites: Record<string, any> = {
  CHARMANDER: require("../assets/pokemon/CHARMANDER.png"),
  CHARMELEON: require("../assets/pokemon/CHARMELEON.png"),
  CHARIZARD: require("../assets/pokemon/CHARIZARD.png"),
  BULBASAUR: require("../assets/pokemon/BULBASAUR.png"),
  IVYSAUR: require("../assets/pokemon/IVYSAUR.png"),
  VENUSAUR: require("../assets/pokemon/VENUSAUR.png"),
  SQUIRTLE: require("../assets/pokemon/SQUIRTLE.png"),
  WARTORTLE: require("../assets/pokemon/WARTORTLE.png"),
  BLASTOISE: require("../assets/pokemon/BLASTOISE.png"),
  EEVEE: require("../assets/pokemon/EEVEE.png"),
  FLAREON: require("../assets/pokemon/FLAREON.png"),
  VAPOREON: require("../assets/pokemon/VAPOREON.png"),
  LEAFEON: require("../assets/pokemon/LEAFEON.png"),
  PIDGEY: require("../assets/pokemon/PIDGEY.png"),
  PIDGEOTTO: require("../assets/pokemon/PIDGEOTTO.png"),
  PIDGEOT: require("../assets/pokemon/PIDGEOT.png"),
  JIGGLYPUFF: require("../assets/pokemon/JIGGLYPUFF.png"),
  WIGGLYTUFF: require("../assets/pokemon/WIGGLYTUFF.png"),
  VULPIX: require("../assets/pokemon/VULPIX.png"),
  NINETALES: require("../assets/pokemon/NINETALES.png"),
  PONYTA: require("../assets/pokemon/PONYTA.png"),
  RAPIDASH: require("../assets/pokemon/RAPIDASH.png"),
  PSYDUCK: require("../assets/pokemon/PSYDUCK.png"),
  GOLDUCK: require("../assets/pokemon/GOLDUCK.png"),
  POLIWAG: require("../assets/pokemon/POLIWAG.png"),
  POLIWHIRL: require("../assets/pokemon/POLIWHIRL.png"),
  POLIWRATH: require("../assets/pokemon/POLIWRATH.png"),
  BELLSPROUT: require("../assets/pokemon/BELLSPROUT.png"),
  WEEPINBELL: require("../assets/pokemon/WEEPINBELL.png"),
  VICTREEBEL: require("../assets/pokemon/VICTREEBEL.png"),
  ODDISH: require("../assets/pokemon/ODDISH.png"),
  GLOOM: require("../assets/pokemon/GLOOM.png"),
  VILEPLUME: require("../assets/pokemon/VILEPLUME.png"),
  GASTLY: require("../assets/pokemon/GASTLY.png"),
  HAUNTER: require("../assets/pokemon/HAUNTER.png"),
  GENGAR: require("../assets/pokemon/GENGAR.png"),
  LITWICK: require("../assets/pokemon/LITWICK.png"),
  LAMPENT: require("../assets/pokemon/LAMPENT.png"),
  CHANDELURE: require("../assets/pokemon/CHANDELURE.png"),
  SHUPPET: require("../assets/pokemon/SHUPPET.png"),
  BANETTE: require("../assets/pokemon/BANETTE.png"),
};

export const pokemonPCSprites: Record<string, any> = {
  charmander: require("../assets/computer/charmander.png"),
  charmeleon: require("../assets/computer/charmeleon.png"),
  charizard: require("../assets/computer/charizard.png"),
  bulbasaur: require("../assets/computer/bulbasaur.png"),
  ivysaur: require("../assets/computer/ivysaur.png"),
  venusaur: require("../assets/computer/venusaur.png"),
  squirtle: require("../assets/computer/squirtle.png"),
  wartortle: require("../assets/computer/wartortle.png"),
  blastoise: require("../assets/computer/blastoise.png"),
  eevee: require("../assets/computer/eevee.png"),
  flareon: require("../assets/computer/flareon.png"),
  vaporeon: require("../assets/computer/vaporeon.png"),
  leafeon: require("../assets/computer/leafeon.png"),
  pidgey: require("../assets/computer/pidgey.png"),
  pidgeotto: require("../assets/computer/pidgeotto.png"),
  pidgeot: require("../assets/computer/pidgeot.png"),
  jigglypuff: require("../assets/computer/jigglypuff.png"),
  wigglytuff: require("../assets/computer/wigglytuff.png"),
  vulpix: require("../assets/computer/vulpix.png"),
  ninetales: require("../assets/computer/ninetales.png"),
  ponyta: require("../assets/computer/ponyta.png"),
  rapidash: require("../assets/computer/rapidash.png"),
  psyduck: require("../assets/computer/psyduck.png"),
  golduck: require("../assets/computer/golduck.png"),
  poliwag: require("../assets/computer/poliwag.png"),
  poliwhirl: require("../assets/computer/poliwhirl.png"),
  poliwrath: require("../assets/computer/poliwrath.png"),
  bellsprout: require("../assets/computer/bellsprout.png"),
  weepinbell: require("../assets/computer/weepinbell.png"),
  victreebel: require("../assets/computer/victreebel.png"),
  oddish: require("../assets/computer/oddish.png"),
  gloom: require("../assets/computer/gloom.png"),
  vileplume: require("../assets/computer/vileplume.png"),
  gastly: require("../assets/computer/gastly.png"),
  haunter: require("../assets/computer/haunter.png"),
  gengar: require("../assets/computer/gengar.png"),
  litwick: require("../assets/computer/litwick.png"),
  lampent: require("../assets/computer/lampent.png"),
  chandelure: require("../assets/computer/chandelure.png"),
  shuppet: require("../assets/computer/shuppet.png"),
  banette: require("../assets/computer/banette.png"),
};

export const pokeballSprites: Record<string, any> = {
  normal: require("../assets/balls/pokeball.png"),
  superball: require("../assets/balls/superball.png"),
};

export const medalSprites: Record<string, any> = {
  stone: require("../assets/medals/stone.png"),
  knuckle: require("../assets/medals/knuckle.png"),
  dynamo: require("../assets/medals/dynamo.png"),
  heat: require("../assets/medals/heat.png"),
  feather: require("../assets/medals/feather.png"),
  rain: require("../assets/medals/rain.png"),
};

export const trainerSprites: Record<string, any> = {
  female: require("../assets/female-trainer.png"),
  male: require("../assets/male-trainer.png"),
  brawly: require("../assets/leaders/brawly.png"),
  flannery: require("../assets/leaders/flannery.png"),
  roxanne: require("../assets/leaders/roxanne.png"),
  wallace: require("../assets/leaders/wallace.png"),
  wattson: require("../assets/leaders/wattson.png"),
  winona: require("../assets/leaders/winona.png"),
};
