export const pokemonSprites: Record<string, any> = {
  CHARMANDER: require("../assets/pokemon/sprites/CHARMANDER.png"),
  CHARMELEON: require("../assets/pokemon/sprites/CHARMELEON.png"),
  CHARIZARD: require("../assets/pokemon/sprites/CHARIZARD.png"),
  BULBASAUR: require("../assets/pokemon/sprites/BULBASAUR.png"),
  IVYSAUR: require("../assets/pokemon/sprites/IVYSAUR.png"),
  VENUSAUR: require("../assets/pokemon/sprites/VENUSAUR.png"),
  SQUIRTLE: require("../assets/pokemon/sprites/SQUIRTLE.png"),
  WARTORTLE: require("../assets/pokemon/sprites/WARTORTLE.png"),
  BLASTOISE: require("../assets/pokemon/sprites/BLASTOISE.png"),
  EEVEE: require("../assets/pokemon/sprites/EEVEE.png"),
  FLAREON: require("../assets/pokemon/sprites/FLAREON.png"),
  VAPOREON: require("../assets/pokemon/sprites/VAPOREON.png"),
  LEAFEON: require("../assets/pokemon/sprites/LEAFEON.png"),
  PIDGEY: require("../assets/pokemon/sprites/PIDGEY.png"),
  PIDGEOTTO: require("../assets/pokemon/sprites/PIDGEOTTO.png"),
  PIDGEOT: require("../assets/pokemon/sprites/PIDGEOT.png"),
  JIGGLYPUFF: require("../assets/pokemon/sprites/JIGGLYPUFF.png"),
  WIGGLYTUFF: require("../assets/pokemon/sprites/WIGGLYTUFF.png"),
  VULPIX: require("../assets/pokemon/sprites/VULPIX.png"),
  NINETALES: require("../assets/pokemon/sprites/NINETALES.png"),
  PONYTA: require("../assets/pokemon/sprites/PONYTA.png"),
  RAPIDASH: require("../assets/pokemon/sprites/RAPIDASH.png"),
  PSYDUCK: require("../assets/pokemon/sprites/PSYDUCK.png"),
  GOLDUCK: require("../assets/pokemon/sprites/GOLDUCK.png"),
  POLIWAG: require("../assets/pokemon/sprites/POLIWAG.png"),
  POLIWHIRL: require("../assets/pokemon/sprites/POLIWHIRL.png"),
  POLIWRATH: require("../assets/pokemon/sprites/POLIWRATH.png"),
  BELLSPROUT: require("../assets/pokemon/sprites/BELLSPROUT.png"),
  WEEPINBELL: require("../assets/pokemon/sprites/WEEPINBELL.png"),
  VICTREEBEL: require("../assets/pokemon/sprites/VICTREEBEL.png"),
  ODDISH: require("../assets/pokemon/sprites/ODDISH.png"),
  GLOOM: require("../assets/pokemon/sprites/GLOOM.png"),
  VILEPLUME: require("../assets/pokemon/sprites/VILEPLUME.png"),
  GASTLY: require("../assets/pokemon/sprites/GASTLY.png"),
  HAUNTER: require("../assets/pokemon/sprites/HAUNTER.png"),
  GENGAR: require("../assets/pokemon/sprites/GENGAR.png"),
  LITWICK: require("../assets/pokemon/sprites/LITWICK.png"),
  LAMPENT: require("../assets/pokemon/sprites/LAMPENT.png"),
  CHANDELURE: require("../assets/pokemon/sprites/CHANDELURE.png"),
  MIMIKYU: require("../assets/pokemon/sprites/MIMIKYU.png"),
};

export const pokeballSprites: Record<string, any> = {
  normal: require("../assets/pokeball.png"),
  superball: require("../assets/superball.png"),
};
